services:
  - memcache
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - mysql -e 'create database appfab_test;'
  - cp config/database-travis.yml config/database.yml
  - rake db:migrate RAILS_ENV=test
rvm:
  - "2.0.0"
script: rake spec cucumber
